# Generated by Django 4.0 on 2021-12-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_commentmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(default='Welcome', max_length=50),
            preserve_default=False,
        ),
    ]
